CREATE TABLE [dbo].[Contact]
(
	[Id] INT IDENTITY (1, 1) UNIQUE,

	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[Job] NVARCHAR(100) NOT NULL,

	[OfficePhone] VARCHAR(20) NOT NULL,
	[CellPhone] VARCHAR(20) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	
	[DateCreated] DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	[LastUpdated] DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT PK_Contact_CellPhone_Email PRIMARY KEY (CellPhone, Email)
)
