CREATE TABLE [dbo].[OrderItem]
(
	[Id] INT IDENTITY (1, 1) UNIQUE,
	[OrderId] INT NOT NULL,
	[Sku] INT NOT NULL,
	[Amount] INT NOT NULL,
	[ActualAmount] INT NULL,
	[DateCreated] DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	[LastUpdated] DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
	CONSTRAINT PK_OrderItem_Id PRIMARY KEY (Id),
	CONSTRAINT FK_OrderItem_OrderId_Order_Id FOREIGN KEY (OrderId) REFERENCES [Order](Id),
	CONSTRAINT FK_OrderItem_Sku_Item_Sku FOREIGN KEY (Sku) REFERENCES [Item](Sku)
)
